export const queryKeys = {
  me: ['me'] as const,
  employees: ['employees'] as const,
  admins: ['admins'] as const,
  deleteRequests: ['delete-requests'] as const,
  invites: ['invites'] as const,
  clients: (filters?: unknown) => ['clients', filters ?? {}] as const,
  projects: (filters?: unknown) => ['projects', filters ?? {}] as const,
  project: (id: string) => ['project', id] as const,
  leads: (filters?: unknown) => ['leads', filters ?? {}] as const,
  tasks: (filters?: unknown) => ['tasks', filters ?? {}] as const,
  task: (id: string) => ['task', id] as const,
  taskMessages: (id: string) => ['task-messages', id] as const,
  sessions: (filters?: unknown) => ['sessions', filters ?? {}] as const,
  screenshots: (filters?: unknown) => ['screenshots', filters ?? {}] as const,
  invoices: (filters?: unknown) => ['invoices', filters ?? {}] as const,
  notifications: ['notifications'] as const,
  proposals: (filters?: unknown) => ['proposals', filters ?? {}] as const,
  proposal: (id: string) => ['proposal', id] as const,
  proposalSummary: ['proposal-summary'] as const,
  reports: (filters?: unknown) => ['reports', filters ?? {}] as const,
  report: (id: string) => ['report', id] as const,
  reportClients: (id: string) => ['report-clients', id] as const,
} as const;
